# Generated by Django 4.0.2 on 2022-03-23 13:54

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Используют для восстановления доступа к аккаунту.', max_length=255, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='./authentication/img/defaultUserImage.svg', upload_to='user-images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже зарегистрирован.'}, help_text='Это значение может содержать до 32 букв, цифр и символов @/./+/-/_.', max_length=32, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Имя пользователя'),
        ),
    ]
